# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/660bc61f-1263-4bd6-a299-3699c02767a8";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker/devicemapper" =
    { device = "/var/lib/docker/devicemapper";
      fsType = "none";
      options = "bind";
    };

  fileSystems."/u" =
    { device = "/dev/disk/by-uuid/acc11a11-de22-44ba-8ecf-97fea1a5d221";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = 16;
}
